name: Compilar APK de Flutter

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Instalar dependencias
      working-directory: AndroidToWeb-main
      run: |
        flutter pub get
        flutter pub add flutter_webrtc web_socket_channel

    - name: Construir APK
      working-directory: AndroidToWeb-main
      run: flutter build apk --release

    - name: Subir APK terminada
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: AndroidToWeb-main/build/app/outputs/flutter-apk/app-release.apk
