name: Compilar APK de Flutter

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Reconstruir Proyecto y Compilar
      run: |
        flutter create --org com.ejemplo mi_app_temporal
        cp lib/main.dart mi_app_temporal/lib/main.dart
        cd mi_app_temporal
        flutter pub add flutter_webrtc web_socket_channel
        flutter pub get
        flutter build apk --release
        cp build/app/outputs/flutter-apk/app-release.apk ../app-release.apk

    - name: Subir APK terminada
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app-release.apk
