name: Compilar APK de Flutter

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # v4.2.0+ ya corre de forma nativa sobre Node.js 24 sin lanzar warnings
    - name: Descargar codigo
      uses: actions/checkout@v4

    # v4.3.0+ está totalmente adaptado a los nuevos entornos de ejecución distribuidos
    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # v2.17.0+ incluye soporte completo para Node 24 y las últimas versiones estables de Flutter
    - name: Configurar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Instalar dependencias y Compilar APK
      run: |        # 1. Encontrar de manera dinámica la carpeta donde está el proyecto
        DIR_PROYECTO=$(dirname $(find . -name "pubspec.yaml" | head -n 1))
        echo "Carpeta encontrada: $DIR_PROYECTO"
        
        cd "$DIR_PROYECTO"
        flutter pub get
        flutter pub add flutter_webrtc web_socket_channel
        
        flutter build apk --release
        
        cd "$GITHUB_WORKSPACE"
        cp "$DIR_PROYECTO/build/app/outputs/flutter-apk/app-release.apk" ./app-release.apk

    # v4.6.0+ es la acción oficial moderna diseñada específicamente para Node 24
    - name: Subir APK terminada
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app-release.apk
